### PR TITLE
Fixing white space bug

### LINKED ISSUE #254: [Bug]: Strip empty space at end of access token
## Description

More annoying when you do it on iPhone, easy to miss. Courses don't fetch if small deviation.

## Steps to reproduce

1. step 1
2. ...

## Expected Behavior

What was expected in place of the bug?

## Screenshots / Recordings (if applicable)

...

### PR DESCRIPTION
**Pull request by iwatger**
Fixes #254 

## Changes Made

- one line

## Checklist
- [x] I have implemented all requirements for this PR and its accompanying issue.
- [x] I have verified my implementation across all edge cases.
- [x] I have ensured my changes compile on macOS & iOS.
- [x] I have resolved all SwiftLint warnings.

### CODE REVIEW

File: CanvasPlusPlayground/Features/Onboarding/SetupView.swift [hunk 1]
```diff
@@ -49,7 +49,7 @@ struct SetupView: View {
         .fontDesign(.rounded)
         .padding()
         .onAppear {
-            tempAccessKey = StorageKeys.accessTokenValue
+            tempAccessKey = StorageKeys.accessTokenValue.trimmingCharacters(in: .whitespacesAndNewlines)
```
Comment (rahulon12) [inline CanvasPlusPlayground/Features/Onboarding/SetupView.swift:52]: Do it in the Task below too, where we set the storage value

**Review by rahulon12 — APPROVED** [review]

File: CanvasPlusPlayground/Features/Onboarding/SetupView.swift (hunk 1 above)
Comment (iwatger) [reply CanvasPlusPlayground/Features/Onboarding/SetupView.swift:52]: Oops, missed that. Fixed now
