### PR TITLE
Use QuickLook to preview files

### LINKED ISSUE #143: [Bug]: "Unable to load file" shows before file loads.
## Description

While the file is loading, the view displays a `ContentUnavailableView` instead of a progress view.

## Steps to reproduce

1. Open a file using `Files`
2. Observe the screen as the file loads

## Expected Behavior

It should show a progress bar/spinner.

## Screenshots / Recordings (if applicable)

https://github.com/user-attachments/assets/62e4a624-402d-4d31-9c28-2fd184932301

### PR DESCRIPTION
**Pull request by rahulon12**
Fixes #143 and #211.

## Changes Made

- Uses `QuickLook` API to preview different file types
- Adds a custom property to `File` to store localURL, if present
- Download icon next to each row if not locally present
- Use sheet on iOS
- Markup, other QuickLook utilities for free on iOS, `ShareLink` on macOS

## Screenshots (if applicable)

Screenshot 2025-02-13 at 3 19 27 PM
Screenshot 2025-02-13 at 3 19 25 PM
Screenshot 2025-02-13 at 3 19 27 PM

An item that "cannot be previewed" looks like this:
Screenshot 2025-02-13 at 5 40 40 PM

## Checklist
- [x] I have implemented all requirements for this PR and its accompanying issue.
- [x] I have verified my implementation across all edge cases.
- [x] I have ensured my changes compile on macOS & iOS.
- [x] I executed `swiftlint --fix` on my code for cleanness.

### CODE REVIEW

**Review by iwatger — APPROVED** [review]
Ran locally and have no qualms!

File: CanvasPlusPlayground/Features/Files/FoldersPageView.swift [hunk 1]
```diff
@@ -95,3 +118,86 @@ struct FoldersPageView: View {
...
+        }
+        .onAppear {
+            // Updates file.localURL if needed
+            _ = CourseFileService.shared
+                .locationForCourseFile(
+                    file,
+                    course: course,
+                    foldersPath: filesVM.traversedFolderIDs
+                )
+        }
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/FoldersPageView.swift:160]: why does this do nothing here? did you mean to set the localURL prop

File: CanvasPlusPlayground/Features/Files/FoldersPageView.swift [hunk 2]
```diff
@@ -95,3 +118,86 @@ struct FoldersPageView: View {
...
+
+    var body: some View {
+        HStack {
+            mainContent
+
+            Spacer()
+
+            if file.localURL == nil {
+                Image(systemName: "arrow.down.circle.dotted")
+            }
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/FoldersPageView.swift:135]: Could we show something if not `nil`? (perhaps a filled download symbol)

File: CanvasPlusPlayground/Features/Files/FileType.swift [hunk 3]
```diff
@@ -6,31 +6,23 @@
...
-        case .pdf: return ".pdf"
-        }
+        "." + fileExtension
+    }
+
+    init(file: File) {
+        self.fileExtension = Self.extensionFromFile(file)
     }
 
     /// Checks the filename for file format, returns nil if File format isn't supported or format was uninferable.
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/FileType.swift:22]: rem comment

File: CanvasPlusPlayground/Features/Files/FileType.swift [hunk 4]
```diff
@@ -6,31 +6,23 @@
...
-    static func fromFile(_ file: File) -> FileType? {
+    static func extensionFromFile(_ file: File) -> String {
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/FileType.swift:23]: Perhaps we should return `FileType` here instead os String, unless I'm missing smthn

File: CanvasPlusPlayground/Features/Files/CourseFileService.swift [hunk 5]
```diff
@@ -101,12 +130,13 @@ struct CourseFileService {
                 }
                 let url = try self.saveCourseFile(courseId: course.id, folderIds: foldersPath, file: file, content: content)
                 print("File successfully saved at \(url.path())")
+
+                return (content, url)
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/CourseFileService.swift:134]: 100MB + resources take a while to download, is there a way to load it lazily for files and videos alike?

Comment (azooz2003-bit) [reply CanvasPlusPlayground/Features/Files/CourseFileService.swift:134]: I think we should also add a download option for downloading files in the BG without opening it. We could have a global & concurrent`DispatchQueue`, so that the file downloads while the user has the app open.

File: CanvasPlusPlayground/Features/Files/CourseFileService.swift [hunk 6]
```diff
@@ -72,18 +75,44 @@ struct CourseFileService {
         return fileURL
     }
 
+    func locationForCourseFile(
+        _ file: File,
+        course: Course,
+        foldersPath: [String]
+    ) -> URL? {
```
Comment (azooz2003-bit) [inline CanvasPlusPlayground/Features/Files/CourseFileService.swift:82]: Can we change the name to smthn like `setLocationForCourseFile` to imply that something is being changed in the file?

**Review by azooz2003-bit — CHANGES_REQUESTED** [review]

File: CanvasPlusPlayground/Features/Files/FoldersPageView.swift (hunk 2 above)
Comment (rahulon12) [reply CanvasPlusPlayground/Features/Files/FoldersPageView.swift:135]: Was following how the `Files` app does it - they show a cloud icon if not downloaded and nothing otherwise

File: CanvasPlusPlayground/Features/Files/FileType.swift (hunk 4 above)
Comment (rahulon12) [reply CanvasPlusPlayground/Features/Files/FileType.swift:23]: Now since you can initialize the `struct`, this just becomes a helper function. I can make it `private` though

File: CanvasPlusPlayground/Features/Files/CourseFileService.swift (hunk 5 above)
Comment (rahulon12) [reply CanvasPlusPlayground/Features/Files/CourseFileService.swift:135]: #230

**Review by azooz2003-bit — APPROVED** [review]

File: CanvasPlusPlayground/Features/Files/FoldersPageView.swift (hunk 2 above)
Comment (rahulon12) [reply CanvasPlusPlayground/Features/Files/FoldersPageView.swift:135]: Will do this in #230
